[input]
cwd = "res/lvgl/"

[generation]
target = "c++20"
classes = {}
functions = { exclude = ["lv_str.*", "lv_mem.*"] }

[generation.namespaces]
include = [{ namespaces = ["file_explorer", "tiny_ttf"] }]
